server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    tomcat:
      max-wait: 5000
      max-active: 10
      test-on-borrow: true
    username: root
    password: toor
    url: jdbc:h2:file:./db/sample_db
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/migration/changelog-master.xml


jwt:
  token:
    secret: muchsecretwow
    expired: 3600000

rest-api:
  url: /api/v1
